### ISSUE TITLE
The method 'existsSync' was called on null.

### ISSUE THREAD

**Issue by Tizoner** [humblerookie/optimized_cached_image#9]
``` 
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'existsSync' was called on null.
```
This error is from here
```
File resizedFile = await FlutterImageCompress.compressAndGetFile(
    file.path, tmpFile.path,
    minWidth: minWidth, minHeight: minHeight, format: format);
if(resizedFile.existsSync()) {
  if (resizedFile.lengthSync() < srcSize) {
    resizedFile.renameSync(file.path);
  } else {
    resizedFile.deleteSync();
  }
}
```
Please do something about it.

**Comment by humblerookie** [comment]
Could you share the image you're trying to load, while its an easy fix, I wish to examine this deeper, since `Flutter Image compress`  seems to be having an issue with this.

**Comment by Tizoner** [comment]
I'm trying to load hundreds of images asynchronously and it works well with 0.1.9 version of your package.
So problem is not in particular image but in the way package (or Flutter Image compress) handles lots of images.

**Comment by humblerookie** [comment]
Fixed this in the latest release. https://github.com/humblerookie/optimized_cached_image/pull/10

**Comment by humblerookie** [comment]
Closing this issue for lack of activity, feel free to reopen once done.
